# -*- coding: utf-8 -*-
"""WQD7006_Lab2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qVBZJcVpemNteY8-dErKVX8roRHs3xqZ

#Lab 2: Data Preprocessing

This notebook provides hands-on practice for data preprocessing concepts.

## 1. Setup & Dataset Overview
"""

# importing necessary libraries and creating dummy data with NaN values
import pandas as pd
import numpy as np

data = {
    "Age": [20, 21, 21, 22, np.nan, 23, 21],
    "BMI": [22.5, 27.8, 27.8, 30.1, np.nan, np.nan, 27.8],
    "StudyHours": [5, 7, 7, 3, 6, 8, 7],
    "FinalScore": [65, 78, 78, 55, 70, 85, 78]
}

df = pd.DataFrame(data)
df

"""## 2. Data Cleaning"""

# What this code is checking?
df.isnull().sum()

# missing value imputation
df["Age"] = df["Age"].fillna(df["Age"].mean())
df["BMI"] = df["BMI"].fillna(df["BMI"].median())
df = df.drop_duplicates()
df

"""## 3. Normalization"""

# Normalization examples using Min Max and Z-score
from sklearn.preprocessing import MinMaxScaler, StandardScaler

scaler = MinMaxScaler()
df_minmax = df.copy()
df_minmax[["Age", "BMI", "StudyHours"]] = scaler.fit_transform(
    df[["Age", "BMI", "StudyHours"]]
)
df_minmax

scaler = StandardScaler()
df_zscore = df.copy()
df_zscore[["Age", "BMI", "StudyHours"]] = scaler.fit_transform(
    df[["Age", "BMI", "StudyHours"]]
)
df_zscore

"""## 4. Data Transformation & Feature Engineering"""

# Transform: discretization
df.loc[:, "BMI_Category"] = pd.cut(
    df.loc[:, "BMI"],
    bins=[0, 18.5, 25, 30, 100],
    labels=["Underweight", "Normal", "Overweight", "Obese"]
)

# Feature engineering: construction
df.loc[:, "StudyEfficiency"] = df.loc[:, "FinalScore"] / df.loc[:, "StudyHours"]

df

"""## 5. Dimentionality Reduction"""

# Principal component analysis (PCA)
from sklearn.decomposition import PCA

features = df[["Age", "BMI", "StudyHours", "FinalScore"]]
pca = PCA(n_components=2)
reduced_data = pca.fit_transform(features)
reduced_data

"""## 6. Reflection

- Why is normalization important?
- When should PCA be applied?
- How would preprocessing differ for text or image data?
"""